version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: aquaclear-backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"
    networks:
      - aquaclear_net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: aquaclear-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - aquaclear_net
    volumes:
      - ./frontend/nginx/dev.conf:/etc/nginx/conf.d/default.conf:ro

networks:
  aquaclear_net:
    driver: bridge
